name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Change to your target SDK

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Pack NuGet package
        run: dotnet pack --configuration Release -o ./nupkg

      - name: Publish to NuGet
        run: dotnet nuget push "./bin/Release/net8.0/*.nupkg" --api-key ${{ secrets.CODENAME399KEY }} --source https://api.nuget.org/v3/index.json
